version: '2'

services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: dcp2015

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dcp2015
